In [4]:
import numpy as np
import torch
q = torch.tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0])
t = torch.argmax(q)
print(t)
torch.floor(t.div(7)) + 1
dictr = {'a': 2, 'b': {'c': 3, 'd': 4}}
len(dictr['b'])

tensor(10)


2

In [6]:
1 % 2

1

In [2]:
A = [1, 2, 3]
print(str(*A))

TypeError: str() argument 2 must be str, not int

In [27]:
A = np.arange(12).reshape((3, 2, 2))
print(A[0])
np.max(A, axis = 0)

[[0 1]
 [2 3]]


array([[ 8,  9],
       [10, 11]])

In [30]:
i, j, k = int(str(123))

TypeError: cannot unpack non-iterable int object

In [1]:
dictt = {'a' : {'1': 1, '3': 1}, 'b': {'max': 3}}

In [6]:
list(dictt['a'].values())

[1, 1]

In [33]:
for i in range(0):
    print(i)

In [40]:
A = [1, 2, 3]
B = np.array([2, 3, 4])
A-B

array([-1, -1, -1])

In [8]:
Qvals = {}
for i in range(0, 3):
        for j in range(0, 3):
            for k in range(0, 3):
                next_actions = {}
                for l in range(i):
                    next_actions[str(l) + str(j) + str(k)] = 0
                for l in range(j):
                    next_actions[str(i) + str(l) + str(k)] = 0
                for l in range(k):
                    next_actions[str(i) + str(j) + str(l)] = 0
                    
                string = str(i) + str(j) + str(k)
                Qvals[string] = next_actions

In [11]:
max(Qvals['121'])

'120'

In [13]:
Qvals['121']

{'021': 0, '101': 0, '111': 0, '120': 0}